apiVersion: v1
kind: Secret
metadata:
  name: rest-api-spring-boot-k8s-secret
data:
  dbUserName: "bXRhbGhh" # "username" encodé en base64
  dbPassword: "VEFMSEFfUGFzc3cwcmQ=" # "password" encodé en base64