apiVersion: v1
kind: Service
metadata:
  name: rest-api-spring-boot-k8s-service
spec:
  selector:
    app: rest-api-spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
